### ISSUE TITLE
Fix URL in package?

### ISSUE THREAD

**Issue by kaushalmodi** [zk-phi/rpn-calc#4]
Hello,

Can you please update the URL in the package to point to the source?

Probably this?

```
--- a/rpn-calc.el
+++ b/rpn-calc.el
@@ -17,7 +17,7 @@
 ;; Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 
 ;; Author: zk_phi
-;; URL: http://hins11.yu-yake.com/
+;; URL: https://github.com/zk-phi/rpn-calc
 ;; Version: 1.1.1
 ;; Package-Requires: ((popup "0.4"))
```

**Comment by kaushalmodi** [comment]
The reason is that when I hit `v` in the `paradox` package to view the source, it opens that other site but it contains no reference to this package. The `v` shortcut is very handy to quickly open the package source repo and review the changes.

**Comment by zk-phi** [comment]
@kaushalmodi,
Updated, thanks!
